apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hourly-date
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: date
            image: busybox
            command:
              - "sh"
              - "-c"
              - "date"
          restartPolicy: OnFailure
