kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: webserver
        image: nginx
        ports:
        - containerPort: 80
      initContainers:
      - name: checkbackend
        image: busybox
        command: ['sh', '-c', 'until nslookup backend.default.svc; do echo
          "Waiting for backend to come up"; sleep 3; done; echo
          "Backend is up, ready to launch web server"']
